/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <Mcu_Interface.h>
#include "Port_Interface.h"
#include "DIO_Interface.h"
#include "Std_Types.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    // Perform MCU and peripheral initialization
    Mcu_Init();
    Mcu_EnumSetPerAPB2(APB2_PER_GPIOA);

    // Perform other initializations
	Port_VidInit();
    Dio_VidInit();

	/* Intilaize led */
	Port_EnumSetterPin(Port_A0, PORT_PIN_OUT|G_PUSH_PULL);

	Mcu_VidRunnable();
	Port_VidRunnable();
	Dio_VidRunnable();

    /* Loop forever */
	for(;;){
		Dio_EnumSetterPin(Dio_A0, STD_ON);
		Dio_VidRunnable();
		for(uint32 i=0;i<110000;i++);      /* To delay led */
		Dio_EnumSetterPin(Dio_A0, STD_OFF);
		Dio_VidRunnable();
		for(uint32 i=0;i<110000;i++);      /* To delay led */
	}
}
